# if: tag IS present

language: python

env:
  global:
    - PORT=7000
    - port=8000
    - REPO=acestream

services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/$REPO .
  - pip install pytest-cov pytest-flake8 codecov

install:
  - docker run -d -e PORT=$PORT -e port=$port -p $port:$PORT $DOCKER_USERNAME/$REPO

script:
  - python -m pytest --cache-clear --cov=. --flake8

deploy:
  - provider: script
    on:
      branch: master
    script: deploy.sh
