if: tag IS present

language: python

env:
  global:
    - PORT=7000
    - port=8000
    - REPO=acestream

services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/$REPO .
  - pip install pytest-cov pytest-flake8 codecov

install:
  - docker run -d -e PORT=$PORT -e port=$port -p $port:$PORT $DOCKER_USERNAME/$REPO

script:
  - python -m pytest --cache-clear --cov=. --flake8

deploy:
  - provider: heroku
    on:
      tags: true
    app: $REPO
    api-key:
      secure: $HEROKU_API_KEY
  - provider: script
    on:
      tags: true
    script: >-
      bash -c 'echo $DOCKER_PASSWORD |
      docker login -u $DOCKER_USERNAME --password-stdin &&
      docker push $DOCKER_USERNAME/$REPO'
