language: python

dist: bionic

python:
  - '3.7'

services:
  - docker

before_install:
  - sudo rm /etc/apt/apt.conf.d/99-travis-apt-proxy
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends python-apsw
  - docker build -t acestream .
  - pip install pytest-cov pytest-flake8 codecov

install:
  - docker run -d -e PORT=7000 -e port=8000 -p 8000:7000 acestream

script:
  - python -m pytest --cache-clear --cov=. --flake8

deploy:
  provider: heroku
  app: acestream
  api-key:
    secure: 
  on:
    tags: true
